version: '3.8'


services:

  postgres-db:
    image: postgres:14.3
    restart: always
    environment:
      #POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432